#!/usr/bin/env ruby

# === borkstrap ===
# https://github.com/alfiepates/borkstrap

require 'optparse'
require 'open-uri'
require 'singleton'

module Borkstrap
	module RequiredKeywordArguments
		def need(keyword)
			raise ArgumentError, "missing keyword #{keyword.inspect}"
		end
	end

	class OptionParser
		def initialize(arguments)
			@arguments = arguments
		end

		def call
			options = {}
			::OptionParser.new do |option_parser|
				option_parser.banner = "Usage: ./borkstrap [options]"

				option_parser.on("-r", "--repo repository", String,
					"Pull a Git repository with a Bork configuration") do |repository|

					options[:repo] =
						if github_shortname?(repository)
							"https://github.com/#{repository}"
						else
							repository
						end
				end
			end.parse!(@arguments)
			options
		end

		private

		def github_shortname?(url)
			url.scan("/").length == 1
		end
	end

	class Cases
		Entry = Struct.new(:key, :value)

		def initialize(cases)
			@cases = cases
		end

		def lookup(query)
			@cases.each { |c| return c.value if c.key === query }
			raise KeyError
		end

		def value?(query)
			@cases.any? { |c| c.value == query }
		end
	end

	class Host
		include Singleton

		def platform
			PLATFORMS.lookup(RUBY_PLATFORM)
		end
	end

	class BrewInstall
		include RequiredKeywordArguments

		def initialize(install_script_url: need(:install_script_url))
			@install_script_url = install_script_url
		end

		def install
			eval open(@install_script_url).read
		end
	end

	class Platform
		include RequiredKeywordArguments

		attr_reader :brew_url

		def initialize(brew_url: need(:brew_url))
			@brew_url = brew_url
		end
	end

	PLATFORMS = Cases.new([
		Cases::Entry.new(/linux/, Platform.new(
			brew_url: "Linuxbrew/install",
		)),
		Cases::Entry.new(/darwin/, Platform.new(
			brew_url: "Homebrew/install",
		)),
	])
end

if __FILE__ == $0
	Borkstrap::OptionParser.new(ARGV).call
end
